### PR TITLE
Update model_factories.md

### PR DESCRIPTION
**Pull request by Ziut3k-dev**
### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Julien-R44** [comment]
Why?Can you explain please?

**Comment by Ziut3k-dev** [comment]
1. In default migration files table defined for name is full_name and in default mode is fullName
2. username() from faker get you a username, but displayName() get you value like "Steven Seagal"

**Comment by Julien-R44** [comment]
Yeah but this is just an example. It has nothing related to the migration included with `web-starter-kit`

**Comment by Ziut3k-dev** [comment]
But people who access the documentation for the first time copy the code and suddenly it doesn't work

**Pull request closed without merging**
